import {expect,test} from "@playwright/test";
import ExcelJS from "exceljs";
import {readFile} from "node:fs/promises";
test("production app has a valid install manifest and reopens routes offline",async({page,context})=>{
  page.on("console",message=>console.log("PWA browser:",message.text()));
  await page.addInitScript(()=>{if(!localStorage.getItem("roco-session-v1"))localStorage.setItem("roco-role","admin");});
  await page.goto("/dashboard");
  const manifest=await (await page.request.get("/manifest.webmanifest")).json();
  console.log("PWA: manifest loaded");
  expect(manifest.display).toBe("standalone");expect(manifest.lang).toBe("fa");
  for(const icon of manifest.icons) {
    const response=await page.request.get(icon.src);expect(response.ok()).toBe(true);
    const buffer=await response.body();
    expect(buffer.readUInt32BE(16)).toBe(Number(icon.sizes.split("x")[0]));
  }
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise<void>(resolve=>navigator.serviceWorker.addEventListener("controllerchange",()=>resolve(),{once:true}));});
  console.log("PWA: worker active");
  const cdp=await context.newCDPSession(page);
  const result=await cdp.send("Page.getAppManifest");
  expect(result.errors).toEqual([]);
  console.log("PWA: browser manifest validation passed");
  await context.setOffline(true);
  await page.reload();
  await expect(page.getByRole("heading",{name:"صبح بخیر، سارا",exact:true})).toBeVisible();
  await page.goto("/requests");
  await expect(page.locator("#main-content").getByRole("heading",{name:"درخواست‌ها",exact:true})).toBeVisible();
  await page.goto("/hr");
  await expect(page.getByRole("heading",{name:"عملیات منابع انسانی",exact:true})).toBeVisible();
  await page.getByRole("button",{name:"پرونده کارکنان",exact:true}).click();
  await expect(page.locator(".employee-directory")).toContainText("سارا احمدی");
  await page.locator(".employee-file").getByRole("button",{name:"ویرایش پرونده",exact:true}).click();
  await page.getByLabel("عنوان شغلی").fill("عنوان ذخیره‌شده آفلاین");
  await page.getByRole("button",{name:"ذخیره پرونده",exact:true}).click();
  await expect(page.locator(".sr-live")).toContainText("ذخیره شد");
  await page.reload();
  await page.getByRole("button",{name:"پرونده کارکنان",exact:true}).click();
  await expect(page.locator(".employee-file")).toContainText("عنوان ذخیره‌شده آفلاین");
  await page.getByRole("button",{name:"مرخصی و مانده",exact:true}).click();
  await page.getByRole("button",{name:"اصلاح مانده سارا احمدی",exact:true}).click();
  await page.getByLabel("مانده جدید پیش از رزرو درخواست‌ها").fill("18");
  await page.getByLabel("دلیل اصلاح مانده").fill("اصلاح آزمایشی مانده در حالت آفلاین");
  await page.getByRole("checkbox",{name:"مقدار، دلیل و اثر بر درخواست‌ها را بررسی کردم."}).check();
  await page.getByRole("button",{name:"ثبت اصلاح مانده",exact:true}).click();
  await expect(page.locator(".sr-live")).toContainText("اصلاح مانده سارا احمدی ذخیره شد");
  await page.goto("/requests"); await page.reload();
  await expect(page.locator(".summary-cards")).toContainText("۱۸ روز");
  await expect(page.locator(".balance-card")).toContainText("۱۷");
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem("roco-leave-v1")!).corrections.length)).toBe(1);
  await page.goto("/hr"); await page.getByRole("button",{name:"پیش‌نمایش",exact:true}).click();
  await page.getByLabel("عنوان اطلاعیه",{exact:true}).fill("پیش‌نویس آفلاین");
  await page.getByLabel("متن اطلاعیه",{exact:true}).fill("این اطلاعیه در مرورگر ذخیره می‌شود و ارسال نشده است.");
  await page.getByRole("button",{name:"ذخیره پیش‌نویس محلی",exact:true}).click();
  await expect(page.getByRole("dialog").locator(".sr-live")).toContainText("ذخیره شد");
  await page.reload(); await page.getByRole("button",{name:"پیش‌نمایش",exact:true}).click();
  await expect(page.getByLabel("عنوان اطلاعیه",{exact:true})).toHaveValue("پیش‌نویس آفلاین");
  await expect(page.locator(".announcement-preview")).toContainText("ارسال نشده");
  await page.keyboard.press("Escape");
  // A lazy-loaded screen also has its chunk precached.
  await page.goto("/design-system");
  await expect(page.getByRole("heading",{name:"راهنمای رابط روکو گایز",exact:true})).toBeVisible();
  // Excel's lazy chunk must work without an earlier online import/export.
  await page.goto("/admin/import-export");
  const workbook=new ExcelJS.Workbook();
  workbook.addWorksheet("کارکنان").addRows([["کد پرسنلی","نام","واحد"],["RG-9001","کارمند نمونه","محصول"]]);
  await page.locator("input[type=file]").setInputFiles({name:"offline.xlsx",mimeType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",buffer:Buffer.from(await workbook.xlsx.writeBuffer())});
  await expect(page.getByRole("heading",{name:"تطبیق ستون‌ها",exact:true})).toBeVisible();
  await page.getByRole("combobox",{name:/قالب فایل/}).selectOption("xlsx");
  const pending=page.waitForEvent("download");
  await page.getByRole("button",{name:"ساخت و دانلود فایل",exact:true}).click();
  const exported=new ExcelJS.Workbook();await exported.xlsx.load(await readFile((await (await pending).path())!));
  expect(exported.worksheets[0].rowCount).toBeGreaterThan(1);
  const cached=await page.evaluate(async()=>{const key=(await caches.keys()).find(k=>k.startsWith("roco-shell-"))!;return (await (await caches.open(key)).keys()).map(r=>new URL(r.url).pathname);});
  expect(cached.some(path=>path.includes("api")||path.includes("roco-session"))).toBe(false);
  console.log("PWA: offline dashboard, requests, shared HR/profile, balances and announcement draft saves/reload, lazy reference and Excel import/export passed");
});
