'use client';

import { useState } from 'react';
import { ArrowDownRight, ArrowUpRight, BarChart3, MoreHorizontal, Plus, Search, Trash2, WalletCards, X } from 'lucide-react';
import { MarketChart } from '@/components/MarketChart';
import { Panel, Stat } from '@/components/UI';
import { assetCost, assetValue, formatMoney, portfolioSummary } from '@/lib/finance';
import { useStore } from '@/lib/store';
import type { AssetType, Currency } from '@/lib/types';

const types: AssetType[] = ['crypto', 'stock', 'fund', 'gold', 'cash', 'property', 'vehicle', 'liability'];

export default function PortfolioPage() {
  const store = useStore();
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [form, setForm] = useState({ symbol: '', name: '', type: 'stock' as AssetType, quantity: 1, averagePrice: 0, currentPrice: 0, currency: 'USD' as Currency });
  const summary = portfolioSummary(store.assets, store.baseCurrency);
  const profit = summary.value - summary.cost;
  const visible = store.assets.filter(asset => `${asset.symbol} ${asset.name}`.toLowerCase().includes(query.toLowerCase()));
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!form.name || !form.symbol) return; store.addAsset({ ...form, symbol: form.symbol.toUpperCase(), dayChange: 0 }); setOpen(false); };

  return <div className="page-wrap portfolio-page">
    <div className="page-title-row"><div><div className="eyebrow"><WalletCards size={13}/> WEALTH CENTER</div><h1>Portfolio</h1><p>Track every asset without giving away your financial privacy.</p></div><button className="primary-button" onClick={() => setOpen(true)}><Plus size={17}/> Add asset</button></div>
    <div className="market-ticker"><div><b>BTCUSD</b><span>68,420.20</span><small className="positive">+2.84%</small></div><div><b>ETHUSD</b><span>3,884.12</span><small className="positive">+1.62%</small></div><div><b>XAUUSD</b><span>3,376.40</span><small className="negative">-0.21%</small></div><div><b>USD/IRT</b><span>92,000</span><small className="positive">+0.38%</small></div><div><b>S&P 500</b><span>6,442.18</span><small className="positive">+0.29%</small></div></div>
    <div className="stat-grid portfolio-stats"><Stat label="Net worth" value={formatMoney(summary.value, store.baseCurrency)}/><Stat label="Total return" value={formatMoney(profit, store.baseCurrency)} change={summary.cost ? profit / summary.cost * 100 : 0}/><Stat label="Today's change" value={formatMoney(summary.day, store.baseCurrency)} change={summary.value ? summary.day / summary.value * 100 : 0}/><Stat label="Assets" value={`${store.assets.length}`} detail={`${new Set(store.assets.map(asset => asset.type)).size} categories`}/></div>
    <Panel className="terminal-chart"><div className="chart-toolbar"><div><span className="asset-badge portfolio">SJ</span><div><b>SJD / {store.baseCurrency}</b><small>Combined portfolio · 1D</small></div></div><div className="chart-tools"><button className="active">Line</button><button>Area</button><button><BarChart3 size={16}/></button><button><MoreHorizontal size={16}/></button></div></div><div className="chart-quote"><strong>{formatMoney(summary.value, store.baseCurrency)}</strong><span className="positive"><ArrowUpRight size={15}/> {formatMoney(summary.day, store.baseCurrency)} today</span></div><MarketChart/><div className="range-switch left"><button>1D</button><button>5D</button><button className="active">1M</button><button>6M</button><button>YTD</button><button>1Y</button><button>5Y</button><button>MAX</button></div></Panel>
    <Panel className="holdings-panel" title="Holdings" eyebrow="ASSET TABLE" action={<div className="table-search"><Search size={15}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Filter assets"/></div>}>
      <div className="holdings-table"><div className="table-head"><span>Asset</span><span>Price</span><span>Holdings</span><span>Avg. price</span><span>P/L</span><span>Day</span><span/></div>{visible.map(asset => { const value = assetValue(asset, store.baseCurrency), cost = assetCost(asset, store.baseCurrency), gain = value - cost; return <div className="holding-row" key={asset.id}><span className="asset-cell"><i className={`asset-badge ${asset.type}`}>{asset.symbol.slice(0,2)}</i><span><b>{asset.name}</b><small>{asset.symbol} · {asset.type}</small></span></span><span><b>{formatMoney(asset.currentPrice, asset.currency)}</b><small>{asset.currency}</small></span><span><b>{formatMoney(value, store.baseCurrency)}</b><small>{asset.quantity.toLocaleString()} units</small></span><span>{formatMoney(asset.averagePrice, asset.currency)}</span><span className={gain >= 0 ? 'positive' : 'negative'}>{gain >= 0 ? '+' : ''}{formatMoney(gain, store.baseCurrency)}</span><span className={asset.dayChange >= 0 ? 'positive' : 'negative'}>{asset.dayChange >= 0 ? <ArrowUpRight size={14}/> : <ArrowDownRight size={14}/>} {Math.abs(asset.dayChange).toFixed(2)}%</span><button className="row-action" onClick={() => store.removeAsset(asset.id)} aria-label={`Remove ${asset.name}`}><Trash2 size={15}/></button></div>; })}</div>
    </Panel>
    {open && <div className="modal-backdrop" onMouseDown={() => setOpen(false)}><form className="modal-card" onSubmit={submit} onMouseDown={event => event.stopPropagation()}><header><div><span>PORTFOLIO</span><h2>Add an asset</h2></div><button type="button" onClick={() => setOpen(false)}><X size={19}/></button></header><div className="form-grid"><label>Symbol<input required value={form.symbol} onChange={event => setForm({...form, symbol:event.target.value})} placeholder="BTC"/></label><label>Name<input required value={form.name} onChange={event => setForm({...form, name:event.target.value})} placeholder="Bitcoin"/></label><label>Asset type<select value={form.type} onChange={event => setForm({...form, type:event.target.value as AssetType})}>{types.map(type => <option key={type}>{type}</option>)}</select></label><label>Currency<select value={form.currency} onChange={event => setForm({...form, currency:event.target.value as Currency})}>{['USD','EUR','GBP','AED','IRR','IRT'].map(value => <option key={value}>{value}</option>)}</select></label><label>Quantity<input type="number" step="any" min="0" value={form.quantity} onChange={event => setForm({...form, quantity:Number(event.target.value)})}/></label><label>Average price<input type="number" step="any" min="0" value={form.averagePrice} onChange={event => setForm({...form, averagePrice:Number(event.target.value)})}/></label><label className="full">Current price<input type="number" step="any" min="0" value={form.currentPrice} onChange={event => setForm({...form, currentPrice:Number(event.target.value)})}/></label></div><footer><button type="button" className="secondary-button" onClick={() => setOpen(false)}>Cancel</button><button className="primary-button">Add to portfolio</button></footer></form></div>}
  </div>;
}
