import { useEffect, useState } from "react";
import { BellIcon, CalendarIcon, CheckCircledIcon, ChevronLeftIcon, DownloadIcon, ExclamationTriangleIcon, ExitIcon, GearIcon, IdCardIcon, MagnifyingGlassIcon, PersonIcon, PlusIcon } from "@radix-ui/react-icons";
import { PageHeader, StatusPill } from "./common";
import { hrStore, leaveBalanceOf, profileOf } from "./hr";
import { employeeStatusLabel, employeeStore } from "./store";
import { Banner, fa } from "./ui";

import { defaultRoster, defaultRosterCodes, readRoster, saveRoster, type Roster, type ShiftCode } from "./roster";

type HrTab = "overview" | "files" | "leave" | "onboarding" | "shifts";
const NOT_RECORDED = "ثبت نشده";
const onboardingItems = ["تکمیل اطلاعات هویتی","امضای قرارداد","تحویل لپ‌تاپ و تجهیزات","معرفی مدیر و تیم","تنظیم شیفت و محل کار","آموزش ورود و خروج"];

export default function HrOperationsPage() {
  const [tab,setTab]=useState<HrTab>("overview");
  const employees=employeeStore.use();
  const hrData=hrStore.use();
  const employeeProblem=employeeStore.useProblem();
  const hrProblem=hrStore.useProblem();
  const storageProblem=employeeProblem||hrProblem;
  const [personCode,setPersonCode]=useState("");
  const hrPeople=employees.map(e=>{const p=profileOf(hrData,e.code),balance=leaveBalanceOf(hrData,e.code);return {...e,role:p.role??NOT_RECORDED,contract:p.contract??NOT_RECORDED,skill:p.skill??NOT_RECORDED,document:p.document??NOT_RECORDED,balance:balance===undefined?NOT_RECORDED:`${fa(balance)} روز`,statusText:employeeStatusLabel[e.status]}});
  const selected=hrPeople.find(p=>p.code===personCode)??hrPeople[0];
  const activeCount=employees.filter(e=>e.status==="active").length;
  const [query,setQuery]=useState("");
  const [rosterError,setRosterError]=useState("");
  const [roster,setRoster]=useState<Roster>(()=>{try{return readRoster()}catch{return defaultRoster()}});
  useEffect(()=>{try{readRoster()}catch{setRosterError("برنامه ذخیره‌شده قابل خواندن نیست؛ برای جلوگیری از حذف داده، ویرایش متوقف شد.")}},[]);
  const published=!!roster.publishedAt;
  const persist=(next:Roster)=>{try{saveRoster(next);setRoster(next);setAnnounce(next.publishedAt?"برنامه شیفت در همین مرورگر منتشر و ذخیره شد.":"پیش‌نویس شیفت در همین مرورگر ذخیره شد.");}catch{setRosterError("ذخیره برنامه ممکن نشد؛ تغییر ثبت نشده است. فضای ذخیره‌سازی مرورگر را بررسی کنید.");}};
  const editShift=(row:number,day:number,value:ShiftCode)=>persist({...roster,publishedAt:null,cells:roster.cells.map((cells,index)=>index===row?cells.map((cell,d)=>d===day?value:cell):cells)});
  const [announce,setAnnounce]=useState("");
  const [checks,setChecks]=useState<boolean[]>(()=>{try{return JSON.parse(localStorage.getItem("roco-onboarding")||"") as boolean[]}catch{return [true,true,true,false,false,false]}});
  useEffect(()=>localStorage.setItem("roco-onboarding",JSON.stringify(checks)),[checks]);
  const tabs: Array<[HrTab,string]> = [["overview","نمای کلی"],["files","پرونده کارکنان"],["leave","مرخصی و مانده"],["onboarding","ورود و خروج کارکنان"],["shifts","برنامه شیفت"]];
  const filtered=hrPeople.filter(item=>item.name.includes(query)||item.code.toLowerCase().includes(query.toLowerCase())||item.department.includes(query));
  const completed=checks.filter(Boolean).length;
  const publish=()=>persist({...roster,publishedAt:new Date().toISOString()});
  return <>
    <PageHeader title="عملیات منابع انسانی" subtitle="چرخه همکاری، مدارک، مرخصی و برنامه‌ریزی تیم" action={<button className="primary-button compact" onClick={()=>setTab("onboarding")}><PlusIcon/> شروع ورود کارمند</button>} />
    <nav className="hr-tabs" aria-label="بخش‌های منابع انسانی">{tabs.map(([key,label])=><button key={key} className={tab===key?"active":""} aria-current={tab===key?"page":undefined} onClick={()=>setTab(key)}>{label}</button>)}</nav>
    {storageProblem&&<p className="field-error" role="alert">{storageProblem}</p>}
    {tab==="overview"&&<div className="hr-overview"><Banner tone="neutral" title="بخشی از آمار نمونه نمایشی است">فقط «کارمند فعال» از فهرست مشترک کارکنان محاسبه می‌شود. ورود و خروج جاری، مرخصی امروز، مدارک، وضعیت حضور و هشدارها نمونه‌اند و هنوز به داده‌های واقعی وصل نیستند.</Banner>
      <section className="hr-kpis"><button className="card" onClick={()=>setTab("files")}><span className="soft-icon"><PersonIcon/></span><strong>{fa(activeCount)}</strong><small>کارمند فعال</small></button><button className="card" onClick={()=>setTab("onboarding")}><span className="soft-icon warning"><IdCardIcon/></span><strong>۴</strong><small>ورود و خروج جاری</small></button><button className="card" onClick={()=>setTab("leave")}><span className="soft-icon"><CalendarIcon/></span><strong>۷</strong><small>مرخصی امروز</small></button><button className="card" onClick={()=>setTab("files")}><span className="soft-icon danger"><ExclamationTriangleIcon/></span><strong>۵</strong><small>مدرک نزدیک انقضا</small></button></section>
      <section className="card live-operations"><div className="card-heading"><div><span className="overline">تصویر زنده امروز</span><h2>وضعیت حضور سازمان</h2></div><StatusPill tone="good">به‌روز</StatusPill></div>{[["حاضر",104,"81%"],["مرخصی",7,"46%"],["تأخیر",9,"62%"],["غایب",8,"54%"]].map(([label,value,width],i)=><div className="operation-row" key={label}><span>{label}</span><div className="progress"><span className={i>1?"alert":""} style={{width:String(width)}}/></div><strong>{fa(value)}</strong></div>)}</section>
      <section className="card hr-alerts"><div className="card-heading"><h2>نیازمند توجه</h2><StatusPill tone="warn">۸ مورد</StatusPill></div>{[["قرارداد رضا نادری","پایان در ۳۰ مهر","bad"],["مدرک هویتی علی مرادی","۲۱ روز تا انقضا","warn"],["برنامه شیفت هفته آینده","هنوز منتشر نشده","neutral"]].map(([title,meta,tone])=><button key={title} onClick={()=>setTab(title.includes("شیفت")?"shifts":"files")}><span><strong>{title}</strong><small>{meta}</small></span><StatusPill tone={tone as "bad"|"warn"|"neutral"}>بررسی</StatusPill><ChevronLeftIcon/></button>)}</section>
      <section className="card announcement-card"><span className="soft-icon"><BellIcon/></span><div><span className="overline">مرکز ارتباطات</span><h2>اطلاعیه‌های کارکنان</h2><p>نمونه نمایشی: اطلاعیه‌ای ارسال یا منتشر نشده است و آماری از مشاهده وجود ندارد.</p></div><button className="secondary-button compact" onClick={()=>setAnnounce("پیش‌نمایش اطلاعیه باز شد")}>پیش‌نمایش</button></section>
    </div>}
    {tab==="files"&&<div className="hr-files-layout"><section className="card employee-directory"><div className="search-field"><MagnifyingGlassIcon/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام، کد یا واحد" aria-label="جستجوی پرونده کارکنان"/></div>{filtered.length===0&&<p className="muted-text">کارمندی پیدا نشد.</p>}{filtered.map((item)=>{return <button className={selected?.code===item.code?"active":""} key={item.code} onClick={()=>setPersonCode(item.code)}><span className="initials">{item.name[0]}</span><span><strong>{item.name}</strong><small>{item.role} • {item.code}</small></span><StatusPill tone={item.status==="active"?"good":item.status==="leave"?"warn":"neutral"}>{item.statusText}</StatusPill></button>})}</section><section className="card employee-file">{!selected?<p className="muted-text">کارمندی برای نمایش وجود ندارد.</p>:<><div className="employee-file-head"><span className="initials large">{selected.name[0]}</span><div><h2>{selected.name}</h2><p>{selected.role} • واحد {selected.department}</p></div><button className="secondary-button compact" onClick={()=>setAnnounce("پرونده برای ویرایش آماده شد")}>ویرایش پرونده</button></div><div className="file-facts"><div><small>قرارداد جاری</small><strong>{selected.contract}</strong></div><div><small>مانده مرخصی</small><strong>{selected.balance}</strong></div><div><small>مهارت شاخص</small><strong>{selected.skill}</strong></div><div><small>وضعیت مدارک</small><strong>{selected.document}</strong></div></div><div className="timeline"><h3>چرخه همکاری</h3><div><span/><strong>ارزیابی سه‌ماهه ثبت شد</strong><small>۲۸ شهریور ۱۴۰۵ • توسط نیما رضایی</small></div><div><span/><strong>تغییر عنوان شغلی</strong><small>۱ تیر ۱۴۰۵ • کارشناس محصول</small></div><div><span/><strong>شروع همکاری</strong><small>۱ مهر ۱۴۰۴ • قرارداد تمام‌وقت</small></div></div><p className="muted-text">نقش، قرارداد، مهارت، مدارک و سابقه بالا نمونه نمایشی‌اند؛ نام، واحد و وضعیت از فهرست مشترک کارکنان می‌آیند.</p></>}</section></div>}
    {tab==="leave"&&<div className="leave-layout"><section className="card leave-policy"><div className="card-heading"><div><span className="overline">سیاست فعال</span><h2>مرخصی استحقاقی ۱۴۰۵</h2></div><button className="secondary-button compact" onClick={()=>setAnnounce("تنظیمات سیاست مرخصی باز شد")}><GearIcon/> تنظیمات</button></div><div className="policy-grid"><div><small>سهم سالانه</small><strong>۲۶ روز</strong></div><div><small>انتقال به سال بعد</small><strong>حداکثر ۹ روز</strong></div><div><small>نحوه تخصیص</small><strong>ماهانه • ۲٫۱۷ روز</strong></div></div><div className="impact-box"><strong>سیاست و تراز نمونه نمایشی است</strong><small>محاسبه خودکار یا تطبیق دفتر مرخصی انجام نمی‌شود. مانده‌ها مقدار نمونه ثبت‌شده در پرونده‌اند؛ «ثبت نشده» یعنی مانده‌ای ثبت نشده است.</small></div></section><section className="card leave-balances"><div className="card-heading"><h2>مانده کارکنان (نمونه)</h2><button className="link-button" onClick={()=>setAnnounce("فایل گزارش مانده‌ها آماده شد")}><DownloadIcon/> دریافت گزارش</button></div>{hrPeople.map(item=><div className="balance-row" key={item.code}><span className="initials">{item.name[0]}</span><span><strong>{item.name}</strong><small>{item.department}</small></span><strong>{item.balance}</strong><button aria-label={`اصلاح مانده ${item.name}`} onClick={()=>setAnnounce(`فرم اصلاح مانده ${item.name} باز شد`)}>اصلاح</button></div>)}</section></div>}
    {tab==="onboarding"&&<div className="onboarding-layout"><Banner tone="neutral" title="نمونه نمایشی">افراد و چک‌لیست‌های ورود و خروج این بخش نمونه‌اند و هنوز به فهرست مشترک کارکنان وصل نیستند.</Banner><section className="card onboarding-card"><div className="person-head"><span className="initials large">آ</span><div><span className="overline">ورود کارمند جدید</span><h2>آرمان حسینی</h2><p>توسعه‌دهنده فرانت‌اند • شروع همکاری ۱۲ مهر</p></div></div><div className="onboarding-progress"><div><strong>{fa(completed)} از {fa(onboardingItems.length)} مرحله</strong><span>{fa(Math.round(completed/onboardingItems.length*100))}٪</span></div><div className="progress"><span style={{width:`${completed/onboardingItems.length*100}%`}}/></div></div><div className="checklist">{onboardingItems.map((label,i)=><label key={label} className={checks[i]?"done":""}><input type="checkbox" checked={!!checks[i]} onChange={()=>setChecks(current=>current.map((value,index)=>index===i?!value:value))}/><span><strong>{label}</strong><small>{i<3?"تکمیل‌شده":"مسئول: منابع انسانی"}</small></span>{checks[i]&&<CheckCircledIcon/>}</label>)}</div></section><aside className="card offboarding-card"><span className="soft-icon warning"><ExitIcon/></span><h2>خروج برنامه‌ریزی‌شده</h2><strong>لیلا موسوی</strong><p>آخرین روز همکاری: ۲۰ مهر ۱۴۰۵</p><ul><li>تحویل تجهیزات</li><li>لغو دسترسی‌ها</li><li>تسویه مانده مرخصی</li></ul><button className="secondary-button" onClick={()=>setAnnounce("چک‌لیست خروج باز شد")}>مشاهده چک‌لیست</button></aside></div>}
    {tab==="shifts"&&<section className="card roster-card"><div className="roster-head"><div><span className="overline">هفته ۱۱ تا ۱۷ مهر</span><h2>برنامه‌ریزی شیفت تیم عملیات</h2><p>تغییرها خودکار در همین مرورگر ذخیره می‌شوند؛ انتشار نمایشی است و برای کارکنان ارسال نمی‌شود.</p></div><div><StatusPill tone={published?"good":"warn"}>{published?"منتشرشده":"پیش‌نویس"}</StatusPill><button className="primary-button compact" onClick={publish} disabled={published||!!rosterError}>{published?<><CheckCircledIcon/> منتشر شد</>:<><BellIcon/> انتشار برنامه</>}</button></div></div>{rosterError&&<p className="field-error" role="alert">{rosterError}</p>}<div className="roster-scroll"><div className="roster-grid roster-header"><strong>کارمند</strong>{["دوشنبه ۱۳","سه‌شنبه ۱۴","چهارشنبه ۱۵","پنجشنبه ۱۶","جمعه ۱۷"].map(day=><span key={day}>{day}</span>)}</div>{(roster.codes??defaultRosterCodes).map((code,row)=>{const item=hrPeople.find(p=>p.code===code)??{name:`${code} (حذف‌شده)`,department:"—",code};return <div className="roster-grid" key={code}><span className="roster-person"><span className="initials">{item.name[0]}</span><span><strong>{item.name}</strong><small>{item.department}</small></span></span>{[0,1,2,3,4].map(day=><select key={day} aria-label={`شیفت ${item.name} ${day+13}`} value={roster.cells[row][day]} disabled={!!rosterError} onChange={e=>editShift(row,day,e.target.value as ShiftCode)}><option value="morning">صبح • ۸:۳۰</option><option value="evening">عصر • ۱۴:۰۰</option><option value="leave">مرخصی</option><option value="off">استراحت</option></select>)}</div>})}</div><div className="roster-footer"><span><CheckCircledIcon/> این برنامه نمونه است؛ پوشش شیفت هنوز خودکار اعتبارسنجی نمی‌شود.</span><span><ExclamationTriangleIcon/> پس از ویرایش برنامه منتشرشده، وضعیت به پیش‌نویس برمی‌گردد.</span></div></section>}
    <div className="sr-live" aria-live="polite">{announce}</div>
  </>;
}
